### PR TITLE
added docker file

### PR DESCRIPTION
**Pull request by pheanex**
Runs fine with me. HowTo:

Build the image (only the first time or if you change something) : 
* "cd docker && docker build -t ingress-ice ."

Start the container:
* "docker run -d -v \<path-to-config-file\>:/.ingress_ice -v \<folder-for-screenshots\>:/screenshots ingress-ice"

Stop the container:
* first find out the name of the container with: "docker ps"
* "docker stop -t 1 \<name of container\>"

### CODE REVIEW

**Comment by nibogd** [comment]
Thank you! Will merge when i get near to a computer. Nice work!

**Comment by nibogd** [comment]
Hm, is it neccessary to use PhantomJS base Docker image? Anyway, we use Phantom from the repo

**Comment by pheanex** [comment]
i used this one since this container ensures phantomjs works absolutely fine since it has the right dependencies and so forth and it makes things easier since i do not have to deal with these issues, i just use it. If we use the binary phantomjs file from this repo we have to deal with the dependencies again ... ;-)

**Comment by nibogd** [comment]
@pheanex Thank you! ;)

**Pull request merged**
