### PR TITLE
Ability to load IITC plugins

### PR DESCRIPTION
**Pull request by serjvanilla**
Add ability to load IITC plugins, and sample links directions plugin. Unfortunately not able to test it.

### CODE REVIEW

**Comment by c2nprds** [comment]
Request specifications(wiki) https://github.com/nibogd/ingress-ice/wiki/Load-IITC-plugins

where did the `pluginsConfig`?

**Comment by nibogd** [comment]
In the next release... Don't have much time now, sorry :(
08 окт. 2015 г. 12:26 пользователь "c2nprds" <notifications@github.com>
написал:

**Comment by nibogd** [comment]
Merged and rewrote a bit. Thank you :+1: .

**Comment by nibogd** [comment]
@c2nprds New version is in the repo

**Pull request merged**
