### PR TITLE
Rewrote bash script

### PR DESCRIPTION
**Pull request by pheanex**
I fixed it mostly for myself => check it out/if you like it merge it
Nevertheless there were some bigger errors iirc in it additionally to the code duplications ;-)

### CODE REVIEW

**Comment by nibogd** [comment]
Hmm... Nice, thank you, but i'd like to stay with my script. Your codestyle is defenitely better :sweat_smile: , but I think we should use `/bin/sh` instead of `/bin/bash` because of portability (not all *nix systems have bash installed by default). 

Also `command -v` [should be used](http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script) for checking if a command present (`which` didn't work for me at all, so i couldn't start the script)

Maybe once I'll rewrite the existing script using some code from yours :smile:

**Comment by pheanex** [comment]
Just out of curiosity: what system are you using?

**Comment by pheanex** [comment]
Ah btw: https://askubuntu.com/questions/141928/what-is-difference-between-bin-sh-and-bin-bash
And iirc you have some "bashisms" in your script anyway ;-)

**Comment by nibogd** [comment]
@pheanex I use Archlinux with bash :) But I've heard some FreeBSD users' complaining about scripts which require bash
Hm, didn't know that now there is no bourne shell... Thank you ;)

**Comment by pheanex** [comment]
@nibogd As far as i know, bash is the most common shell (except freebsd, but who uses that anyway ;-)) I assume that the target usergroup for ingress-ice is mostly linux,mac and maybe a bit windows.
=> Bash is the most common shell and using it would make things a lot more stable.

**Comment by nibogd** [comment]
@pheanex Hmm, you've convinced me :) Will change `/bin/sh` into `/bin/bash`

**Comment by pheanex** [comment]
;-) If we now are using bash, then you might consider running some checks on this script with for example http://www.shellcheck.net/# (in short: it warns you about a lot of things, that will easily break).
An additional source for common bash-pitfalls and general tips is http://mywiki.wooledge.org/BashGuide (hint: with my PR i fixed all the things both addresses recommend ;-) )

**Comment by nibogd** [comment]
Thank you, I'll try :)

вс, 30 авг. 2015 г. в 18:14, PHeanEX <notifications@github.com>:

**Pull request closed without merging**
