### PR TITLE
Fix launch command in start.sh and hide portals level filter

### PR DESCRIPTION
**Pull request by adostes**
Fix launch command in start.sh
Hide portals level filter

### CODE REVIEW

**Comment by nibogd** [comment]
I've done hiding `#filters_container` in latest commit, will relese 2.0.1 soon
Also deleted debug screenshots :)
Thank you again for your help!

**Comment by adostes** [comment]
Awesome for the hiding!
You're right for the exec. It didn't work on my ubuntu machine so I removed 'exec ./' but the problem is not with the exec command, it's with the relative path to ./phantomjs
My phantomjs is installed globally using npm, doesnt using exec ./phantomjs imply it's in the current directory?

**Comment by nibogd** [comment]
It's supposed that you download it in "releases" section (download link in readme) so executable would be included. That's why the link is relative, it's for those users who don't have phantomjs installed globally. I'll push executables into master branch tomorrow :)

**Comment by nibogd** [comment]
Now binaries are in master :)

**Comment by nibogd** [comment]
So, I'm closing the issue. Good luck in ingress, @adostes ! :-)

**Comment by adostes** [comment]
This is great, thanks!

**Pull request closed without merging**
